-- Change TIMESTAMP columns to TIMESTAMP WITH TIME ZONE to properly handle UTC
ALTER TABLE users
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC',
    ALTER COLUMN last_login_at SET DATA TYPE TIMESTAMP WITH TIME ZONE USING last_login_at AT TIME ZONE 'UTC';
