-- Revert TIMESTAMP WITH TIME ZONE back to TIMESTAMP
ALTER TABLE users
    ALTER COLUMN created_at SET DATA TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at SET DATA TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC',
    ALTER COLUMN last_login_at SET DATA TYPE TIMESTAMP USING last_login_at AT TIME ZONE 'UTC';
